#!/usr/bin/env python3
"""docsmith setup_profile — create/extend ~/.docsmith/profile.yaml (portable).

This is the CANONICAL writer for the docsmith brand profile. It is deliberately
dependency-free for *writing* (pure stdlib) so it runs on any machine and inside
any agent — Claude Code, OpenClaw, Hermes, Codex, … — not just where PyYAML is
installed. (Reading an existing file to APPEND uses PyYAML when available and
falls back to a safe textual append otherwise.)

Two ways in:

  • interactive (default): prompts for each brand attribute, loops over orgs, then
    writes the profile. This is what `make-pdf`'s Step 0 runs on first use.

  • non-interactive (`--json`): reads a JSON org object — or a JSON array of org
    objects — from stdin (or `--json-file PATH`) and writes it. This is the path
    the `npx` installer drives after collecting answers in its own UI.

The profile is the **list-of-orgs** shape `build.py:resolve_org` expects: each
entry is one self-contained organisation the skill can brand a document as, and
one is picked per run by `company`. Honours $DOCSMITH_HOME (default ~/.docsmith).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

# The eight self-contained attributes of one org entry, in canonical order.
FIELDS = [
    "company",
    "author",
    "email",
    "logo",
    "wordmark",
    "website",
    "default_confidentiality",
    "copyright",
]

CONFIDENTIALITY_CHOICES = ["", "Public", "Internal", "Confidential", "Restricted"]

HEADER = (
    "# ~/.docsmith/profile.yaml — one entry per org you brand documents as.\n"
    "# One org is picked per run by company name (or --company / --logo / front-matter).\n"
    "# Generated by docsmith setup_profile.py — plain YAML, edit freely.\n"
)

FIELD_HELP = {
    "company": "Organization name (required — this is what the cover/footer prints)",
    "author": "Primary author / docs contact",
    "email": "Contact email",
    "logo": "Path to a square SVG/PNG logo (renders ~40px tall in footers); blank = none",
    "wordmark": "Text shown when no logo is set (e.g. ACME)",
    "website": "Organization website URL",
    "default_confidentiality": "Public / Internal / Confidential / Restricted ('' = none)",
    "copyright": "Copyright notice, e.g. © 2026 Acme Corp",
}


def docsmith_home() -> Path:
    return Path(os.environ.get("DOCSMITH_HOME", str(Path.home() / ".docsmith")))


def profile_path() -> Path:
    return docsmith_home() / "profile.yaml"


def ensure_home() -> None:
    """Create the docsmith home + the dirs Step 0 expects (best-effort)."""
    home = docsmith_home()
    for sub in ("", "template", "cache/diagrams", "logo"):
        try:
            (home / sub).mkdir(parents=True, exist_ok=True)
        except Exception:
            pass


# ---------- YAML emission (hand-rolled — no PyYAML needed to WRITE) -------------

def _yaml_str(value) -> str:
    """Emit a value as a double-quoted YAML scalar, safely escaped.

    Double-quoting sidesteps every YAML special-char pitfall (`:`, `#`, leading
    `-`, unicode like ©). We only need to escape backslash and double-quote, and
    flatten any stray newline so one field stays on one line.
    """
    s = "" if value is None else str(value)
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", "")
    return f'"{s}"'


def _emit_org(org: dict) -> str:
    lines = []
    for i, key in enumerate(FIELDS):
        prefix = "- " if i == 0 else "  "
        lines.append(f"{prefix}{key}: {_yaml_str(org.get(key, ''))}")
    return "\n".join(lines)


def render_profile(orgs: list[dict]) -> str:
    body = "\n\n".join(_emit_org(o) for o in orgs)
    return f"{HEADER}\n{body}\n"


def normalize(org: dict) -> dict:
    """Coerce one org to the canonical 8-field dict, filling blanks for missing keys."""
    out = {k: "" for k in FIELDS}
    for k, v in (org or {}).items():
        if k in out:
            out[k] = "" if v is None else str(v)
    return out


# ---------- existing-file handling --------------------------------------------

def _looks_like_list(text: str) -> bool:
    """True if the (comment-stripped) file is a YAML *list* — safe to textually append."""
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        return stripped.startswith("- ")
    return False


def _read_existing_orgs(path: Path):
    """Return existing orgs as a list of dicts, or None if it can't be parsed as a list.

    Uses PyYAML when importable (docsmith's own env has it); returns None for a
    legacy dict profile so the caller refuses to append into it.
    """
    try:
        import yaml  # type: ignore

        data = yaml.safe_load(path.read_text())
        if isinstance(data, list):
            return [normalize(o) for o in data if isinstance(o, dict)]
        return None  # legacy dict / scalar — not appendable
    except ImportError:
        return None
    except Exception:
        return None


def write_profile(orgs: list[dict], mode: str) -> Path:
    """Write `orgs` to the profile path under `mode` ∈ {overwrite, append, skip}.

    - overwrite: replace the file with exactly `orgs`.
    - append:    add `orgs` after the existing entries (re-emitting cleanly when
                 PyYAML is present; otherwise a guarded textual append).
    - skip:      leave the file untouched.
    """
    orgs = [normalize(o) for o in orgs]
    ensure_home()
    path = profile_path()

    if not path.exists():
        path.write_text(render_profile(orgs))
        return path

    if mode == "skip":
        return path

    if mode == "overwrite":
        path.write_text(render_profile(orgs))
        return path

    # append
    existing = _read_existing_orgs(path)
    if existing is not None:
        path.write_text(render_profile(existing + orgs))
        return path
    # PyYAML unavailable: fall back to a safe textual append, but only if the file
    # is already a YAML list (never corrupt a legacy dict profile).
    text = path.read_text()
    if _looks_like_list(text):
        joined = "\n\n".join(_emit_org(o) for o in orgs)
        if not text.endswith("\n"):
            text += "\n"
        path.write_text(text + "\n" + joined + "\n")
        return path
    raise SystemExit(
        f"refusing to append: {path} is not a list-of-orgs profile. "
        "Re-run with --mode overwrite to replace it, or edit it by hand."
    )


# ---------- interactive --------------------------------------------------------

def _prompt(label: str, help_text: str = "", default: str = "") -> str:
    if help_text:
        print(f"    · {help_text}")
    suffix = f" [{default}]" if default else ""
    try:
        raw = input(f"  {label}{suffix}: ").strip()
    except EOFError:
        return default
    return raw or default


def _prompt_confidentiality(default: str = "") -> str:
    print("  default_confidentiality:")
    for i, c in enumerate(CONFIDENTIALITY_CHOICES):
        print(f"    {i}) {c or '(none)'}")
    raw = input("    choose 0-4 [0]: ").strip()
    if not raw:
        return default
    try:
        idx = int(raw)
        if 0 <= idx < len(CONFIDENTIALITY_CHOICES):
            return CONFIDENTIALITY_CHOICES[idx]
    except ValueError:
        pass
    # treat free text as a literal value
    return raw


def interactive() -> int:
    print("\ndocsmith — set up your brand profile")
    print(f"  → writes {profile_path()}\n")
    orgs: list[dict] = []
    while True:
        n = len(orgs) + 1
        print(f"Organization #{n}")
        company = _prompt("company", FIELD_HELP["company"])
        if not company:
            if orgs:
                break
            print("  (company is required for the first org)\n")
            continue
        org = {"company": company}
        for key in FIELDS:
            if key in ("company", "default_confidentiality"):
                continue
            org[key] = _prompt(key, FIELD_HELP[key])
        org["default_confidentiality"] = _prompt_confidentiality()
        orgs.append(normalize(org))
        again = input("\nAdd another organization? [y/N]: ").strip().lower()
        print()
        if again not in ("y", "yes"):
            break

    if not orgs:
        print("nothing to write — aborted.")
        return 1

    mode = "overwrite"
    if profile_path().exists():
        ans = input(
            f"{profile_path()} already exists — [a]ppend / [o]verwrite / [s]kip? [a]: "
        ).strip().lower()
        mode = {"o": "overwrite", "s": "skip", "a": "append", "": "append"}.get(ans, "append")

    path = write_profile(orgs, mode)
    print(f"\n✓ profile {mode} → {path}")
    return 0


# ---------- non-interactive (--json) -------------------------------------------

def from_json(raw: str, mode: str) -> int:
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"invalid JSON: {e}", file=sys.stderr)
        return 2
    if isinstance(data, dict):
        data = [data]
    if not isinstance(data, list) or not all(isinstance(o, dict) for o in data):
        print("expected a JSON org object or array of org objects", file=sys.stderr)
        return 2
    orgs = [normalize(o) for o in data]
    if not orgs:
        print("no orgs in JSON payload", file=sys.stderr)
        return 2
    if not [o for o in orgs if o.get("company")]:
        print("at least one org must have a non-empty 'company'", file=sys.stderr)
        return 2
    path = write_profile(orgs, mode)
    print(str(path))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Create or extend ~/.docsmith/profile.yaml.")
    ap.add_argument("--json", action="store_true",
                    help="read a JSON org object / array from stdin (non-interactive)")
    ap.add_argument("--json-file", help="read the JSON payload from this file instead of stdin")
    ap.add_argument("--mode", choices=["overwrite", "append", "skip"], default="append",
                    help="how to treat an existing profile (default: append)")
    ap.add_argument("--print-path", action="store_true",
                    help="print the resolved profile path and exit")
    args = ap.parse_args()

    if args.print_path:
        print(str(profile_path()))
        return 0

    if args.json or args.json_file:
        raw = Path(args.json_file).read_text() if args.json_file else sys.stdin.read()
        return from_json(raw, args.mode)

    return interactive()


if __name__ == "__main__":
    raise SystemExit(main())
